//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RitchieBlackmore.Classes.EntityFramworcDbContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationType
    {
        public OperationType()
        {
            this.StatisticsOperation = new HashSet<StatisticsOperation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StatisticsOperation> StatisticsOperation { get; set; }
    }
}
