//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RitchieBlackmore.Classes.EntityFramworcDbContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsOperation
    {
        public int OperationId { get; set; }
        public int ProductId { get; set; }
        public System.Guid UserId { get; set; }
        public int OperationTypeId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual OperationType OperationType { get; set; }
        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
