//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RitchieBlackmore.Classes.EntityFramworcDbContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsOperation
    {
        public int OperationId { get; set; }
        public int ProductId { get; set; }
        public System.Guid UserId { get; set; }
        public int OperationTypeId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual OperationType OperationType { get; set; }
        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
